services:
  gateway:
    container_name: gateway
    image: gateway
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gateway.dev
    command: server start  
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080