services:
  gateway:
    container_name: gateway
    image: gateway
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gateway.dev
    command: server start  
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8080
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mstudio
      - POSTGRES_USER=mstudio
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mstudio" ]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local
  postgres:
    driver: local